version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node-superfetch
    versions:
    - 0.2.2
  - dependency-name: nodejs-base64
    versions:
    - 2.0.0
